# Generated by Django 3.0 on 2019-12-10 19:59

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminTools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_bn', models.CharField(max_length=100, verbose_name='Full Name of Student - BN')),
                ('full_name_en', models.CharField(max_length=100, verbose_name='Full Name of Student - EN')),
                ('photo', models.ImageField(default='std_img.png', upload_to='students')),
                ('std_id', models.CharField(blank=True, default=students.models.increment_unique_student_id, max_length=100, null=True, unique=True, verbose_name='Student ID')),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=1, verbose_name='Gender')),
                ('religion', models.CharField(choices=[('I', 'Islam'), ('H', 'Hindu')], default='I', max_length=1, verbose_name='Religion')),
                ('father_name_bn', models.CharField(max_length=100, verbose_name='Father Name - BN')),
                ('father_name_en', models.CharField(max_length=100, verbose_name='Father Name - EN')),
                ('mother_name_bn', models.CharField(max_length=100, verbose_name='Mother Name - BN')),
                ('mother_name_en', models.CharField(max_length=100, verbose_name='Mother Name - EN')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth of Student')),
                ('mobile_number', models.PositiveIntegerField(verbose_name='Mobile Number')),
                ('optional_mobile_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mobile Number')),
                ('email_field', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('last_school', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('address_opt', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('academic_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminTools.AcademicSection')),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminTools.AcademicSession')),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminTools.BloodGroup')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminTools.SchoolClass')),
            ],
        ),
    ]
