# Generated by Django 3.0 on 2019-12-13 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminTools', '0002_admissionapproval_schoolinformation'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='std_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminTools.StudentGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='std_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='union',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminTools.Union'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='upazilla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminTools.Upazilla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='word_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminTools.WordNo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='zilla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminTools.Zilla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_school',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_id',
            field=models.CharField(blank=True, default=students.models.increment_unique_student_id, editable=False, max_length=100, null=True, unique=True, verbose_name='Student ID'),
        ),
    ]
