# Generated by Django 3.0 on 2019-12-10 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminTools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='std_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminTools.StudentGroup'),
        ),
        migrations.AddField(
            model_name='student',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminTools.Union'),
        ),
        migrations.AddField(
            model_name='student',
            name='upazilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminTools.Upazilla'),
        ),
        migrations.AddField(
            model_name='student',
            name='word_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminTools.WordNo'),
        ),
        migrations.AddField(
            model_name='student',
            name='zilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminTools.Zilla'),
        ),
    ]
