# Generated by Django 3.0 on 2019-12-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminTools', '0001_initial'),
        ('students', '0002_auto_20191210_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminTools.Union'),
        ),
        migrations.AlterField(
            model_name='student',
            name='upazilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminTools.Upazilla'),
        ),
        migrations.AlterField(
            model_name='student',
            name='word_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminTools.WordNo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminTools.Zilla'),
        ),
    ]
