# Generated by Django 3.0 on 2019-12-10 21:08

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191210_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_id',
            field=models.CharField(blank=True, default=students.models.increment_unique_student_id, editable=False, max_length=100, null=True, unique=True, verbose_name='Student ID'),
        ),
    ]
