# Generated by Django 3.0 on 2019-12-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20191210_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_status',
            field=models.BooleanField(default=False),
        ),
    ]
